# Vector calculus with SageMath

## Part 4: Changing coordinates

This notebook illustrates some vector calculus capabilities of SageMath within the 3-dimensional Euclidean space. The corresponding tools have been developed within
the [SageManifolds](https://sagemanifolds.obspm.fr) project.

Click [here](https://raw.githubusercontent.com/sagemanifolds/SageManifolds/master/Notebooks/SM_vector_calc_change.ipynb) to download the notebook file (ipynb format). To run it, you must start SageMath with the Jupyter interface, via the command `sage -n jupyter`

First we set up the notebook to display math formulas using LaTeX formatting:

In [ ]:
%display latex

## Cartesian coordinates

We start by declaring the 3-dimensional Euclidean space $\mathbb{E}^3$, with $(x,y,z)$ as Cartesian coordinates:

In [ ]:
E.<x,y,z> = EuclideanSpace()
print(E)
E

Euclidean space E^3


Euclidean space E^3

$\mathbb{E}^3$ is endowed with the chart of Cartesian coordinates:

In [ ]:
E.atlas()

[Chart (E^3, (x, y, z))]

Let us denote by `cartesian` the chart of Cartesian coordinates:

In [ ]:
cartesian = E.cartesian_coordinates()
cartesian

The access to the individual coordinates is performed via the square bracket operator:

In [ ]:
cartesian[1]

In [ ]:
cartesian[:]

Thanks to use of `<x,y,z>` when declaring `E`, the Python variables `x`, `y` and `z` have been created (i.e. there is no need to declare them by something like `y = var('y')`); they represent the coordinates $(x,y,z)$ as symbolic expressions:

In [ ]:
y is cartesian[2]

In [ ]:
type(y)

Each of the Cartesian coordinates spans the entire real line:

In [ ]:
cartesian.coord_range()

Being the only coordinate chart created so far, `cartesian` is the default chart on `E`:

In [ ]:
cartesian is E.default_chart()

$\mathbb{E}^3$ is endowed with the orthonormal vector frame $(e_x, e_y, e_z)$ associated with Cartesian coordinates: 

In [ ]:
E.frames()

Let us denote it by `cartesian_frame`:

In [ ]:
cartesian_frame = E.cartesian_frame()
cartesian_frame

In [ ]:
cartesian_frame is E.default_frame()

Each element of this frame is a unit vector field; for instance, we have $e_x\cdot e_x = 1$:

In [ ]:
e_x = cartesian_frame[1]
e_x

In [ ]:
e_x.dot(e_x).expr()

as well as $e_x\cdot e_y = 0$:

In [ ]:
e_y = cartesian_frame[2]
e_x.dot(e_y).expr()

## Spherical coordinates

Spherical coordinates are introduced by

In [ ]:
spherical.<r,th,ph> = E.spherical_coordinates()
spherical

We have

In [ ]:
spherical[:]

In [ ]:
spherical.coord_range()

$\mathbb{E}^3$ is now endowed with two coordinate charts:

In [ ]:
E.atlas()

The change-of-coordinate formulas have been automatically implemented during the above call `E.spherical_coordinates()`:

In [ ]:
E.coord_change(spherical, cartesian).display()

In [ ]:
E.coord_change(cartesian, spherical).display()

$\mathbb{E}^3$ is also now endowed with three vector frames:

In [ ]:
E.frames()

The second one is the coordinate frame of spherical coordinates, while the third one is the standard orthonormal frame associated with spherical coordinates. For Cartesian coordinates, the coordinate frame and the orthonormal frame coincide: it is $(e_x,e_y,e_z)$. For spherical coordinates, the orthonormal frame is denoted $(e_r,e_\theta,e_\phi)$ and is returned by the method `spherical_frame()`:

In [ ]:
spherical_frame = E.spherical_frame()
spherical_frame

We may check that it is an orthonormal frame:

In [ ]:
es = spherical_frame
[[es[i].dot(es[j]).expr() for j in E.irange()] for i in E.irange()]

The orthonormal spherical frame expressed in terms of the Cartesian one: 

In [ ]:
for vec in spherical_frame:
    show(vec.display(cartesian_frame, spherical))

The reverse transformation:

In [ ]:
for vec in cartesian_frame:
    show(vec.display(spherical_frame, spherical))

The orthonormal frame $(e_r,e_\theta,e_\phi)$ expressed in terms on the coordinate frame $\left(\frac{\partial}{\partial r}, \frac{\partial}{\partial\theta}, \frac{\partial}{\partial \phi}\right)$ (the latter being returned by the method `frame()` acting on the chart `spherical`):

In [ ]:
for vec in spherical_frame:
    show(vec.display(spherical.frame(), spherical))

## Cylindrical coordinates

Cylindrical coordinates are introduced by

In [ ]:
cylindrical.<rh,ph,z> = E.cylindrical_coordinates()
cylindrical

We have

In [ ]:
cylindrical[:]

In [ ]:
rh is cylindrical[1]

In [ ]:
cylindrical.coord_range()

$\mathbb{E}^3$ is now endowed with three coordinate charts:

In [ ]:
E.atlas()

The transformations linking the cylindrical coordinates to the Cartesian ones are

In [ ]:
E.coord_change(cylindrical, cartesian).display()

In [ ]:
E.coord_change(cartesian, cylindrical).display()

$\mathbb{E}^3$ is also now endowed with five vector frames:

In [ ]:
E.frames()

The orthonormal frame associated with cylindrical coordinates is $(e_\rho, e_\phi, e_z)$:

In [ ]:
cylindrical_frame = E.cylindrical_frame()
cylindrical_frame

We may check that it is an orthonormal frame:

In [ ]:
ec = cylindrical_frame
[[ec[i].dot(ec[j]).expr() for j in E.irange()] for i in E.irange()]

The orthonormal cylindrical frame expressed in terms of the Cartesian one: 

In [ ]:
for vec in cylindrical_frame:
    show(vec.display(cartesian_frame, cylindrical))

The reverse transformation:

In [ ]:
for vec in cartesian_frame:
    show(vec.display(cylindrical_frame, cylindrical))

The orthonormal cylindrical frame expressed in terms of the spherical one: 

In [ ]:
for vec in cylindrical_frame:
    show(vec.display(spherical_frame, spherical))

The reverse transformation:

In [ ]:
for vec in spherical_frame:
    show(vec.display(cylindrical_frame, spherical))

The orthonormal frame $(e_\rho,e_\phi,e_z)$ expressed in terms on the coordinate frame $\left(\frac{\partial}{\partial\rho}, \frac{\partial}{\partial\phi}, \frac{\partial}{\partial z}\right)$ (the latter being returned by the method `frame()` acting on the chart `cylindrical`):

In [ ]:
for vec in cylindrical_frame:
    show(vec.display(cylindrical.frame(), cylindrical))

## Coordinates of a point

We introduce a point $p\in \mathbb{E}^3$ via the generic SageMath syntax for creating an element from its parent (here $\mathbb{E}^3$), i.e. the call operator `()`, with the coordinates of the point as the first argument:

In [ ]:
p = E((-1, 1,0), chart=cartesian, name='p')
print(p)

Actually, since the Cartesian coordinates are the default ones, the above writting is equivalent to

In [ ]:
p = E((-1, 1,0), name='p')
print(p)

The coordinates of $p$ in a given coordinate chart are obtained by letting the corresponding chart act on $p$:

In [ ]:
cartesian(p)

In [ ]:
spherical(p)

In [ ]:
cylindrical(p)

A point defined from its spherical coordinates:

In [ ]:
q = E((4,pi/3,pi), chart=spherical, name='q')
print(q)

In [ ]:
spherical(q)

In [ ]:
cartesian(q)

In [ ]:
cylindrical(q)

## Expressions of a scalar field in various coordinate systems

Let us define a scalar field on $\mathbb{E}^3$ from its expression in Cartesian coordinates:

In [ ]:
f = E.scalar_field(x^2+y^2 - z^2, name='f')

Note that since the Cartesian coordinates are the default ones, we did not specify them in the above definition. Thanks to the known coordinate transformations, the expression of $f$ in terms of other coordinates is automatically computed:

In [ ]:
f.display()

We can limit the output to a single coordinate system:

In [ ]:
f.display(cartesian)

In [ ]:
f.display(cylindrical)

The coordinate expression in a given coordinate system is obtained via the method `expr()`

In [ ]:
f.expr()  # expression in the default chart (Cartesian coordinates)

In [ ]:
f.expr(spherical)

In [ ]:
f.expr(cylindrical)

The value of $f$ at points $p$ and $q$:

In [ ]:
f(p)

In [ ]:
f(q)

Of course, we may define a scalar field from its coordinate expression in a chart that is not the default one:

In [ ]:
g = E.scalar_field(r^2, chart=spherical, name='g')

Instead of using the keyword argument `chart`, one can pass a dictionary as the first argument, with the chart as key:

In [ ]:
g = E.scalar_field({spherical: r^2}, name='g')

In [ ]:
g.display()

## Expression of a vector field in various frames

Let us introduce a vector field on $\mathbb{E}^3$ by its components in the Cartesian frame. Since the latter is the default vector frame on $\mathbb{E}^3$, it suffices to write:

In [ ]:
v = E.vector_field(-y, x, z^2, name='v')
v.display()

Equivalently, a vector field can be defined directly from its expansion on the Cartesian frame: 

In [ ]:
ex, ey, ez = cartesian_frame[:]
v = -y*ex + x*ey + z^2*ez
v.display()

Let us provide `v` with some name, as above:

In [ ]:
v.set_name('v')
v.display()

The components of $v$ are returned by the square bracket operator:

In [ ]:
v[1]

In [ ]:
v[:]

The expression of $v$ in terms of the orthonormal spherical frame is obtained by

In [ ]:
v.display(spherical_frame)

We note that the components are still expressed in the default chart (Cartesian coordinates). To have them expressed in the spherical chart, it suffices to pass the latter as a second argument to `display()`:

In [ ]:
v.display(spherical_frame, spherical)

Again, the components of $v$ are obtained by means of the square bracket operator, by specify the vector frame as first argument, and the coordinate chart as the last one:

In [ ]:
v[spherical_frame, 1]

In [ ]:
v[spherical_frame, 1, spherical]

In [ ]:
v[spherical_frame, :, spherical]

Similarly, the expression of $v$ in terms of the cylindrical frame is

In [ ]:
v.display(cylindrical_frame, cylindrical)

In [ ]:
v[cylindrical_frame,:,cylindrical]

The value of the vector field $v$ at point $p$:

In [ ]:
vp = v.at(p)
print(vp)

In [ ]:
vp.display()

In [ ]:
vp.display(spherical_frame.at(p))

In [ ]:
vp.display(cylindrical_frame.at(p))

The value of the vector field $v$ at point $q$:

In [ ]:
vq = v.at(q)
print(vq)

In [ ]:
vq.display()

In [ ]:
vq.display(spherical_frame.at(q))

In [ ]:
vq.display(cylindrical_frame.at(q))

## Changing the default coordinates and default vector frame

At any time, one may change the default coordinates by the method `set_default_chart`:

In [ ]:
E.set_default_chart(spherical)

Then

In [ ]:
f.expr()

In [ ]:
v.display()

Note that the default vector frame is still the Cartesian one; to change to the orthonormal spherical frame, we use

In [ ]:
E.set_default_frame(spherical_frame)

Then

In [ ]:
v.display()

In [ ]:
v.display(cartesian_frame, cartesian)

# Sage
## Lightning Preview

Let's first get a small feel for sage by seeing some standard operations and what typical use looks like through a series of trivial, mostly unconnected examples.

In [ ]:
2+3

You can also subtract, multiply, divide, exponentiate...

    >>> 3-2
    1
    >>> 2*3
    6
    >>> 2^3
    8
    >>> 2**3 # (also exponentiation)
    8
    
There is an order of operations, but these things work pretty much as you want them to work. You might try out several different operations.

Sage includes a lot of functionality, too. For instance,

In [ ]:
factor(-1008)

In [ ]:
list(factor(1008))

In the background, Sage is actually calling on pari/GP to do this factorization. Sage bundles lots of free and open source math software within it (which is why it's so large), and provides a common access point. The great thing here is that you can often use sage without needing to know much pari/GP (or other software).

Sage knows many functions and constants, and these are accessible.

In [1]:
sin(pi)

NameError: name 'sin' is not defined

In [ ]:
exp(2)

Sage tries to internally keep expressions in exact form. To present approximations, use `N()`.

In [ ]:
N(exp(2))

In [ ]:
pi

In [ ]:
N(pi)

You can ask for a number of digits in the approximation by giving a `digits` keyword to `N()`.

In [ ]:
N(pi, digits=60)

There are some benefits to having smart representations. In many computer algebra systems, computing (sqrt(2))^2 doesn't give you back 2, due to finite floating point arithmetic. But in sage, this problem is sometimes avoided.

In [ ]:
sqrt(2)

In [ ]:
sqrt(2)**2

Of course, there are examples where floating point arithmetic gets in the way.

In sage/python, integers have unlimited digit length. Real precision arithmetic is a bit more complicated, which is why sage tries to keep exact representations internally. We don't go into tracking digits of precision in sage, but it is usually possible to prescribe levels of precision.

Sage is written in python. You can use python functions in sage. [You can also import python libraries in sage, which extends sage's reach significantly]. The `range` function in python counts up to a given number, starting at 0.

In [ ]:
range(16)

In [3]:
A = matrix(4,4, range(16))
A

[ 0  1  2  3]
[ 4  5  6  7]
[ 8  9 10 11]
[12 13 14 15]

In [9]:
B = matrix(4,4, range(-5, 11))
B

[-5 -4 -3 -2]
[-1  0  1  2]
[ 3  4  5  6]
[ 7  8  9 10]

Sage can be smart about using the same operators in different contexts. (i.e. sage is very polymorphic). Multiplying, adding, subtracting, and dividing matrices works as expected.

In [10]:
A*B

[ 26  32  38  44]
[ 42  64  86 108]
[ 58  96 134 172]
[ 74 128 182 236]

There are two sorts of ways that functions are called in sage. For some functions, you create the object (in this case, the matrix A), type a dot `.`, and then call the function.

In [6]:
A.charpoly()

x^4 - 30*x^3 - 80*x^2

There are some top-level functions as well.

In [7]:
factor(A.charpoly())

x^2 * (x^2 - 30*x - 80)

Sometimes you start with an object, such as a matrix, and you wonder what you can do with it. Sage has very good tab-completion and introspection in its notebook interface.

Try typing 

    A.
    
and hit `<Tab>`. Sage should display a list of things it thinks it can do to the matrix A.

### Warning

Note that on CoCalc or external servers, tab completion sometimes has a small delay.

In [5]:
A.eigenvalues?

Docstring:     
   Return a sequence of the eigenvalues of a matrix, with
   multiplicity. If the eigenvalues are roots of polynomials in "QQ",
   then "QQbar" elements are returned that represent each separate
   root.

   If the option "extend" is set to "False", only eigenvalues in the
   base ring are considered.

   EXAMPLES:

      sage: a = matrix(ZZ, 4, range(16)); a
      [ 0  1  2  3]
      [ 4  5  6  7]
      [ 8  9 10 11]
      [12 13 14 15]
      sage: sorted(a.eigenvalues(), reverse=True)
      [32.46424919657298?, 0, 0, -2.464249196572981?]

      sage: a = matrix([(1, 9, -1, -1),
      ....:             (-2, 0, -10, 2),
      ....:             (-1, 0, 15, -2),
      ....:             (0, 1, 0, -1)])
      sage: a.eigenvalues()
      [-0.9386318578049146?,
       15.50655435353258?,
       0.2160387521361705? - 4.713151979747493?*I,
       0.2160387521361705? + 4.713151979747493?*I]

   A symmetric matrix "a + a.transpose()" should have real eigenvalues

      sage: b = 

Some of these are more meaningful than others, but you have a list of options. If you want to find out what an option does, like `A.eigenvalues()`, then type 

    A.eigenvalues?
    
and hit enter.

In [5]:
A.adjugate??

Docstring:
   Return the adjugate matrix of "self" (that is, the transpose of the
   matrix of cofactors).

   Let M be an n x n-matrix. The adjugate matrix of M is the n
   x n-matrix N whose (i, j)-th entry is (-1)^{i + j} \det(M_{j,
   i}), where M_{j,i} is the matrix M with its j-th row and i-th
   column removed. It is known to satisfy NM = MN = \det(M)I.

   EXAMPLES:

      sage: M = Matrix(ZZ,2,2,[5,2,3,4]); M
      [5 2]
      [3 4]
      sage: N = M.adjugate(); N
      [ 4 -2]
      [-3  5]
      sage: M * N
      [14  0]
      [ 0 14]
      sage: N * M
      [14  0]
      [ 0 14]
      sage: M = Matrix(QQ, 2, 2, [5/3,2/56, 33/13,41/10]); M
      [  5/3  1/28]
      [33/13 41/10]
      sage: N = M.adjugate(); N
      [ 41/10  -1/28]
      [-33/13    5/3]
      sage: M * N
      [7363/1092         0]
      [        0 7363/1092]

   An alias is "adjoint_classical()", which replaces the deprecated
   "adjoint()" method:

      sage: M.adjoint()
      ...: DeprecationWarning: adj

In [4]:
A.eigenvalues()

[0, 0, -2.464249196572981?, 32.46424919657298?]

If you're really curious about what's going on, you can type

    A.eigenvalues??
    
which will also show you the implementation of that functionality. (You usually don't need this).

There is a lot of domain-specific functionality within sage as well. We won't dwell too much on any particular functionality in this tutorial, but for example sage knows about elliptic curves.

In [ ]:
E = EllipticCurve([1,2,3,4,5])
E

In [ ]:
# Tab complete me to see what's available
E.

In [ ]:
E.conductor()

In [ ]:
E.rank()

Sage knows about complex numbers as well. Use `i` or `I` to mean a $\sqrt{-1}$.

In [ ]:
(1+2*I) * (pi - sqrt(5)*I)

In [ ]:
c = 1/(sqrt(3)*I + 3/4 + sqrt(29)*2/3)

Sage tries to keep computations in exact form. So `c` is stored with perfect representations of square roots.

In [ ]:
c

But we can have sage give numerical estimates of objects by calling `N()` on them.

In [ ]:
N(c)

In [ ]:
N(c, 20) # Keep 20 "bits" of information

As one more general topic before we jump into a few deeper examples, sage is also very good at representing objects in latex. Use `latex(<object>)` to give a latex representation.

In [ ]:
latex(c)

In [ ]:
latex(E)

In [ ]:
latex(A)

You can have sage print the LaTeX version in the notebook by using `pretty_print`

In [ ]:
pretty_print(A)

## Basic Algebra

In [ ]:
H = DihedralGroup(6)
H.list()

In [ ]:
a = H[1]
a

In [ ]:
a.order()

In [ ]:
b = H[2]
b

In [ ]:
a*b

In [ ]:
for elem in H:
    if elem.order() == 2:
        print elem

In [ ]:
# Or, in the "pythonic" way
elements_of_order_2 = [elem for elem in H if elem.order() == 2]
elements_of_order_2

In [ ]:
rand_elem = H.random_element()
rand_elem

In [ ]:
G_sub = H.subgroup([rand_elem])
G_sub

In [ ]:
# Explicitly using elements of a group
H("(1,2,3,4,5,6)") * H("(1,5)(2,4)")

### Exercises

The real purpose of these exercises are to show you that it's often possible to use tab-completion to quickly find out what is and isn't possible to do within sage.

1. What things does sage know about this subgroup? Can you find the cardinality of the subgroup? (Note that the subgroup is generated by a random element, and your subgroup might be different than your neighbor's). Can you list all subgroups of the dihedral group in sage?

2. Sage knows other groups as well. Create a symmetric group on 5 elements. What does sage know about that? Can you verify that S5 isn't simple? Create some cyclic groups?

## Changing the Field

It's pretty easy to work over different fields in sage as well. I show a few examples of this

In [ ]:
# It may be necessary to use `reset('x')` if x has otherwise been defined
K.<alpha> = NumberField(x**3 - 5)

In [ ]:
K

In [ ]:
alpha

In [ ]:
alpha**3

In [ ]:
(alpha+1)**3

In [ ]:
GF?

In [ ]:
F7 = GF(7)

In [ ]:
a = 2/5
a

In [ ]:
F7(a)

In [ ]:
var('x')

In [ ]:
eqn = x**3 + sqrt(2)*x + 5 == 0
a = solve(eqn, x)[0].rhs()

In [ ]:
a

In [ ]:
latex(a)

In [ ]:
pretty_print(a)

In [ ]:
# Also RR, CC
QQ

In [ ]:
K.<b> = QQ[a]

In [ ]:
K

In [ ]:
a.minpoly()

In [ ]:
K.class_number()

### Exercise

Sage tries to keep the same syntax even across different applications. Above, we factored a few integers. But we may also try to factor over a number field. You can factor 2 over the Gaussian integers by:

1. Create the Gaussian integers. The constructor CC[I] works.
2. Get the Gaussian integer 2 (which is programmatically different than the typical integer 2), by something like `CC[I](2)`.
3. `factor` that 2.



## Some Calculus And Symbolic Manipulation

In [ ]:
# Let's declare that we want x and y to mean symbolic variables
x = 1
y = 2
print(x+y)

reset('x')
reset('y')
var('x')
var('y')

print(x+y)

In [ ]:
solve(x^2 + 3*x + 2, x)

In [ ]:
solve(x^2 + y*x + 2 == 0, x)

In [ ]:
# Nonlinear systems with complicated solutions can be solved as well
var('p,q')
eq1 = p+1==9
eq2 = q*y+p*x==-6
eq3 = q*y**2+p*x**2==24
s = solve([eq1, eq2, eq3, y==1], p,q,x,y)
s

In [ ]:
s[0]

In [ ]:
latex(s[0])

$$\left[p = 8, q = \left(-26\right), x = \left(\frac{5}{2}\right), y = 1\right]$$

In [ ]:
# We can also do some symbolic calculus
f = x**2 + 2*x + 1
f

In [ ]:
diff(f, x)

In [ ]:
integral(f, x)

In [ ]:
F = integral(f, x)
F(x=1)

In [ ]:
diff(sin(x**3), x)

In [ ]:
# Compute the 4th derivative
diff(sin(x**3), x, 4)

In [ ]:
# We can try to foil sage by giving it a hard integral
integral(sin(x)/x, x)

In [ ]:
f = sin(x**2)
f

In [ ]:
# And sage can give Taylor expansions
f.taylor(x, 0, 20)

In [ ]:
f(x,y)=y^2+1-x^3-x
contour_plot(f, (x,-pi,pi), (y,-pi,pi))

In [ ]:
contour_plot(f, (x,-pi,pi), (y,-pi,pi), colorbar=True, labels=True)

In [ ]:
# Implicit plots
f(x,y) = -x**3 + y**2 - y + x + 1
implicit_plot(f(x,y)==0,(x,0,2*pi),(y,-pi,pi))

### Exercises

1. Experiment with the above examples by trying out different functions and plots.

2. Sage can do partial fractions for you as well. To do this, you first define your function you want to split up. Suppose you call it `f`. Then you use `f`.partial_fraction(x). Try this out

3. Sage can also create 3d plots. Create one. Start by looking at the documentation for `plot3d`.

Of the various math software, sage+python provides my preferred plotting environment. I have used sage to create plots for notes, lectures, classes, experimentation, and publications. You can quickly create good-looking plots. For example, I used sage/python extensively in creating [this note for my students](http://davidlowryduda.com/an-intuitive-overview-of-taylor-series/) on Taylor Series (which is a classic "hard topic" that students have lots of questions about, at least in the US universities I'm familiar with. To this day, about 1/6 of the traffic to my website is to see that page).

As a non-trivial example, I present the following interactive plot. 

In [ ]:
@interact
def g(f=sin(x), c=0, n=(1..30),
      xinterval=range_slider(-10, 10, 1, default=(-8,8), label="x-interval"),
      yinterval=range_slider(-50, 50, 1, default=(-3,3), label="y-interval")):
    x0 = c
    degree = n
    xmin,xmax = xinterval
    ymin,ymax = yinterval
    p   = plot(f, xmin, xmax, thickness=4)
    dot = point((x0,f(x=x0)),pointsize=80,rgbcolor=(1,0,0))
    ft = f.taylor(x,x0,degree)
    pt = plot(ft, xmin, xmax, color='red', thickness=2, fill=f)
    show(dot + p + pt, ymin=ymin, ymax=ymax, xmin=xmin, xmax=xmax)
    html('$f(x)\;=\;%s$'%latex(f))
    html('$P_{%s}(x)\;=\;%s+R_{%s}(x)$'%(degree,latex(ft),degree))

## Tutorial

In [ ]:
%display latex
integrate(exp(-x**2), x, 0, infinity)

In [ ]:
f(x) = sqrt(3*x-2)
integral(2*pi*f(x)*sqrt(1+diff(f,x)**2), x, 0, 5)
show(revolution_plot3d(f, (x,0,5), parallel_axis='x', \
        show_curve=True, opacity=0.7), aspect_ratio=1)

## Integers, Rationals, etc.
Several rings are defined by default in Sagemath.
See e.g., [https://doc.sagemath.org/html/en/reference/rings_standard/index.html].

In [ ]:
a = 1/2
print(a)

In [ ]:
type(a)

In [ ]:
print(1/2 + 3/4 + 5/6)

You can check in which ring a number belongs

In [ ]:
3/4 in QQ

In [ ]:
3/4 in ZZ

In [ ]:
f = 1.2
type(f)

In [ ]:
print(f in RR, f in QQ)

and convert a number if it belongs to the ring

In [ ]:
QQ(f)

try f.<TAB> to discover methods associated with numbers in a ring.
    
You can also use complex numbers

In [ ]:
c = 1/2 + 3/4*i
print(c)
print(type(c))

In [ ]:
c + 1.5

In [ ]:
c^2

By default, symbol `i` is used for complex numbers. If you have already used it elsewhere, you can restore its default value using `reset(i)`.

In [ ]:
i = 4
print(i)
reset('i')
print(i)

Sagemath can manipulate very large numbers.

In [ ]:
a = 100
print(a)
print(factor(a))
print(factorial(100))
print(factor(factorial(100)))

## Symbolic math

In [ ]:
x = var('x')
f(x) = 1 - sin(x)^2
print(f)
show(f)
print(latex(f))
plot(f)

In [ ]:
print(f(pi/2))
print(f(pi/4))

In [ ]:
show(f.differentiate())
show(f.differentiate(2))
show(f.simplify_trig())

In [ ]:
g = (f^2).integrate(x)
show(g)
plot(g)

Symbolic functions on multiple variables.

In [ ]:
x, y, z = var('x y z')
f(x, y, z) = x + 2*y + 3*z^2
show(f)

In [ ]:
show(f(1))
show(f(1, 2))
show(f(1, 2, 3))

In [ ]:
g = f + 2*x^3
show(g)

Solve an equation.

In [ ]:
x = var('x')
f(x) = x^2 + 3*x + 2
solve(f, x)

In [ ]:
solve([f(x) == 1], x)

In [ ]:
x, y = var('x y')
solve([2*x^2 + 3*y == 1], x)

## Linear algebra
[https://doc.sagemath.org/html/en/reference/matrices/index.html]


In [ ]:
A = Matrix([[1,2,3],[3,2,1],[1,1,1]])
print(A)
print(latex(A))
show(A)

In [ ]:
show(A.kernel())

In [ ]:
A.eigenvalues()

In [ ]:
show(A^2 + A.transpose())

In [ ]:
A = Matrix([[1,2,3],[3,2,1],[1,1,1/2]])
show(A)

In [ ]:
show(A^2)

## Combinatorics
[https://doc.sagemath.org/html/en/reference/combinat/index.html]

In [ ]:
P5 = Partitions(5)
P5

In [ ]:
list(P5)

## Graph Theory
[https://doc.sagemath.org/html/en/reference/graphs/index.html]

In [ ]:
G = graphs.PetersenGraph()
print("diameter =", G.diameter())
print("treewidth =", G.treewidth())
show(G)

In [ ]:
C = G.coloring()
print(C)
G.plot(partition=C)

You can list the induced connected subgraphs on 4 vertices

In [ ]:
len(list(G.connected_subgraph_iterator(4)))

List the simple paths from 0 to 3

In [ ]:
for P in G.shortest_simple_paths(0, 3):
    print(P)

Compute a Hamiltonian cycle

In [ ]:
G = graphs.DodecahedralGraph()
H = G.hamiltonian_cycle()
G.plot(edge_colors={'red': H.edges()})

Check isomorphisms between graphs

In [ ]:
G = graphs.Grid2dGraph(3, 4)
H = G.relabel(inplace=False)  # relabel the vertices 0..n-1
G.is_isomorphic(H)

Search for a subgraph isomorphic to a given graph

In [ ]:
G = graphs.EuropeMap()
B = graphs.BullGraph()
G.subgraph_search(B).show()

Display all graphs or order 5 (may require optional package `nauty`, which gives more options)

In [ ]:
glist= [g for g in graphs(5)]
graphs_list.show_graphs(glist)

## Linear programming
[https://doc.sagemath.org/html/en/thematic_tutorials/linear_programming.html]
[https://doc.sagemath.org/html/en/reference/numerical/sage/numerical/mip.html]

Simple interface for `glpk`, `PPL`, `cbc`, `cplex`, `gurobi`.

In [ ]:
def dominating_set(G):
    """
    Return a minimum dominating set of ``G``
    """
    from sage.numerical.mip import MixedIntegerLinearProgram
    p = MixedIntegerLinearProgram(maximization=False)
    b = p.new_variable(binary=True, name='b')
    for u in G:
        # Either u in D or a neighbor of u is in D
        p.add_constraint(b[u] + p.sum(b[v] for v in G.neighbors(u)) >= 1)
    # We want to maximize the size of the dominating set
    p.set_objective(p.sum(b[u] for u in G))
    p.solve()
    b_val = p.get_values(b)
    return [v for v in G if b_val[v]]

G = graphs.RandomUnitDiskGraph(100, radius=.2, seed=0)
dom = dominating_set(G)
print(dom)
G.plot(vertex_colors={'red':dom})

To display a graph, we can also use the `d3.js` interface. It will display the graph in a new window of your web browser.

In [ ]:
G = graphs.RandomTree(100)
G.show(method='js')

## Use Cython

Static compiler for Python and the extended Cython programming language. With Cython, you can
* Code functions using both Python and C/C++
* Make interface with C/C++ code
* Get better performances for critical functions
* Used to interface external code (cliquer, bliss, nauty, gmp, etc.) 

Sagemath uses extensively Cython ([https://cython.org]) to make interfaces with various C/C++ libraries and get better performances for various functions.

In [ ]:
def sum_py(n):
    s = 0
    for i in range(n):
        s += i
    return s

In [ ]:
%%cython
def sum_cy(n):
    s = 0
    for i in range(n):
        s += i
    return s

In [ ]:
%%cython
def sum_cy2(int n):
    cdef long s = 0
    cdef int i
    for i in range(n):
        s += i
    return s

In [ ]:
n = 10**7
print(timeit("sum_py(10**5)"))
print(timeit("sum_cy(10**5)"))
print(timeit("sum_cy2(10**5)"))

and you can do much more with Cython outside of jupyter...